apiVersion: v1
kind: Service
metadata:
  name: {{ include "permitio-pdp.fullname" . }}
  labels:
    {{- include "permitio-pdp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "permitio-pdp.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
    {{- end }}
