name: Lint and Test Charts

on:
  push:
    branches:
      - "**"
      - "*"
      - "!master"
      - "!gh-pages"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # ratchet:actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # ratchet:azure/setup-helm@v1
        with:
          version: v3.4.1

      - name: Run chart-testing (lint)
        run: helm lint charts/*
